spring:
  datasource:
    url: jdbc:mysql://localhost:10041/lowcode_passport_20130428v1?characterEncoding=utf-8&createDatabaseIfNotExist=true
oauth-clients:
  # 这里必须全部填上
  list:
    - client-id: lc
      client-secret: 12345
      ids:
        - app
        - content
        - record
      scopes: all
      redirectUris:
        - http://localhost:10060/#/app
        - https://localhost:10060/#/app
        - http://localhost:3000/#/app